# Generated by Django 4.0.6 on 2022-07-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_port', '0002_content_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='ContactForm',
        ),
    ]
