# Generated by Django 4.0.6 on 2022-07-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_port', '0003_rename_content_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('rent', models.IntegerField(max_length=10)),
                ('deposit', models.IntegerField(max_length=10)),
                ('maintenance', models.IntegerField(max_length=10)),
                ('phone', models.IntegerField(max_length=10)),
                ('mail', models.CharField(max_length=50)),
                ('uid', models.IntegerField(max_length=10)),
            ],
        ),
    ]
