# Generated by Django 4.0.6 on 2022-07-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_port', '0004_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='deposit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='maintenance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
