# Generated by Django 4.0.6 on 2022-07-23 20:39

from django.db import migrations, models
import rent_a_port.models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_port', '0005_alter_property_deposit_alter_property_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='img',
            field=models.ImageField(null=True, upload_to=rent_a_port.models.filepath),
        ),
    ]
