# Generated by Django 4.0.6 on 2022-07-23 21:08

from django.db import migrations, models
import rent_a_port.models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_port', '0006_property_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='img',
            new_name='in_img',
        ),
        migrations.AddField(
            model_name='property',
            name='out_img',
            field=models.ImageField(null=True, upload_to=rent_a_port.models.filepath),
        ),
    ]
