# Generated by Django 4.0.6 on 2022-07-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_port', '0007_rename_img_property_in_img_property_out_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='out_img',
        ),
    ]
