# Generated by Django 4.0.6 on 2022-07-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_port', '0009_property_out_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_mail', models.CharField(max_length=50)),
            ],
        ),
    ]
