# Generated by Django 4.1 on 2022-09-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_port', '0010_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
