# Generated by Django 4.1 on 2022-09-09 12:32

from django.db import migrations, models
import rent_a_port.models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_port', '0011_property_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('Message', models.CharField(default='Empty', max_length=500)),
                ('rent', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('maintenance', models.IntegerField()),
                ('BHK', models.CharField(default='1 BHK', max_length=15)),
                ('Floor_number', models.CharField(default='Ground floor', max_length=10)),
                ('Pet_allowed', models.CharField(default='No', max_length=15)),
                ('Parking', models.CharField(default='Yes', max_length=15)),
                ('Property_type', models.CharField(default='House', max_length=15)),
                ('Posted_by', models.CharField(default='House', max_length=15)),
                ('Agreement_duration', models.CharField(default='No', max_length=15)),
                ('Electricity_water', models.CharField(default='No', max_length=15)),
                ('Available_from', models.DateField()),
                ('Posted_on', models.DateTimeField(auto_now_add=True)),
                ('phone', models.IntegerField()),
                ('mail', models.CharField(max_length=50)),
                ('in_img', models.ImageField(null=True, upload_to=rent_a_port.models.filepath)),
                ('out_img', models.ImageField(null=True, upload_to=rent_a_port.models.filepath)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
    ]
