# Generated by Django 4.1 on 2022-09-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_port', '0012_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('appointment_date_time', models.DateTimeField()),
                ('message', models.CharField(max_length=500)),
                ('user_id', models.IntegerField()),
                ('property_id', models.IntegerField()),
                ('uuid', models.CharField(max_length=100)),
                ('appointment_set', models.BooleanField()),
            ],
        ),
    ]
