# Generated by Django 4.1 on 2022-09-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_port', '0014_alter_site_floor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='Agreement_duration',
            field=models.CharField(default='Charges not included', max_length=15),
        ),
        migrations.AlterField(
            model_name='site',
            name='Electricity_water',
            field=models.CharField(default='Charges not included', max_length=20),
        ),
    ]
