# Generated by Django 4.1 on 2022-09-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_port', '0016_alter_site_agreement_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
